### PR TITLE
fix(payments): use stripe/cjs resource types in reconciliationService

### PR DESCRIPTION
**Pull request by georgyia**
## Why
`main` fails `npx tsc --noEmit` after PRs #149 and #159 landed in parallel:

```
src/payments/providers/stripe/reconciliationService.ts(54,26): error TS2694:
  Namespace 'StripeConstructor' has no exported member 'Issuing'.
src/payments/providers/stripe/reconciliationService.ts(55,28): error TS2694:
  Namespace 'StripeConstructor' has no exported member 'Issuing'.
```

#149 added `Stripe.Issuing.Card` / `Stripe.Issuing.Transaction` annotations; #159 (Stripe 16 → 22) removed those namespace exports from the default `Stripe` import. Neither PR conflicted textually, but their semantic combination is broken on `main`.

## What
Switch to the same `stripe/cjs/resources/Issuing` resource-type imports that `cardService.ts`, `webhookHandler.ts`, and `checkoutSimulator.ts` already use post-Stripe 22. Drop the now-unused default `Stripe` import.

## Verification
- `npx tsc --noEmit` → clean
- `npx eslint src/payments/providers/stripe/reconciliationService.ts` → clean
- `npx jest --testPathIgnorePatterns=tests/integration` → 38 suites / 412 tests pass

No runtime behaviour change — types only.

## Summary by CodeRabbit

* **Refactor**
  * Internal code improvements to payment reconciliation service with no changes to functionality or user-facing behavior.

[Review Change Stack](https://app.coderabbit.ai/change-stack/JonasBaeumer/AgentWallet/pull/168)

### CODE REVIEW

**Comment by georgyia** [comment]
Heads up: `main` is currently failing `npx tsc --noEmit` because **#149** and **#159** merged in parallel and the resulting combination breaks two type references in `reconciliationService.ts`. This PR is the minimal types-only fix — same import pattern already used by `cardService.ts` / `webhookHandler.ts` / `checkoutSimulator.ts`. All checks are green; needs **1 approval** to satisfy the branch ruleset, then it can be merged.

**Comment by JonasBaeumer** [comment]
Nice yes this solves the broken CI and fixes the broken import. Thanks!

**Review by JonasBaeumer — APPROVED** [review]
